/**
 * Catálogo demo basado en referencias reales de jeyjo.es (precios PVP con IVA 21 %).
 * Los precios P1/P2 del seed se calculan sin IVA; P2 ≈ −13 % sobre P1 (tarifa B2B).
 */

export type JeyjoSupplierSeed = {
  erpCode: string
  name: string
  type: 'wholesaler' | 'manufacturer' | 'distributor' | 'other'
  baseImageUrl?: string
}

export type JeyjoProductSeed = {
  skuErp: string
  title: string
  slug: string
  supplierErpCode: string
  categorySlug: string
  shortDescription: string
  /** PVP con IVA tal como aparece en jeyjo.es */
  priceWithVat: number
  vatRate?: number
  erpStock: number
  oemRef?: string
  ean?: string
  mainWholesaleRef?: string
  facetColor?: string
  facetMaterial?: string
  ecoLabel?: boolean
  keywords?: string[]
}

/** Marcas / proveedores visibles en jeyjo.es */
export const JEYJO_SUPPLIERS: JeyjoSupplierSeed[] = [
  { erpCode: 'BIC', name: 'BIC', type: 'manufacturer' },
  { erpCode: 'NAVIGATOR', name: 'Navigator', type: 'manufacturer' },
  { erpCode: 'FELLOWES', name: 'Fellowes', type: 'manufacturer' },
  { erpCode: 'REXEL', name: 'Rexel', type: 'manufacturer' },
  { erpCode: 'DYMO', name: 'DYMO', type: 'manufacturer' },
  { erpCode: 'ESSELTE', name: 'Esselte', type: 'manufacturer' },
  { erpCode: 'OLEF', name: 'Olef', type: 'manufacturer' },
  { erpCode: 'PETRUS', name: 'Petrus', type: 'manufacturer' },
  { erpCode: 'RAPID', name: 'Rapid', type: 'manufacturer' },
  { erpCode: 'DAHLE', name: 'Dahle', type: 'manufacturer' },
  { erpCode: 'UNI-BALL', name: 'Uni-Ball', type: 'manufacturer' },
  { erpCode: 'STAEDTLER', name: 'Staedtler', type: 'manufacturer' },
  { erpCode: 'NOBO', name: 'Nobo', type: 'manufacturer' },
  { erpCode: 'FOROFIS', name: 'Forofis', type: 'manufacturer' },
  { erpCode: 'U-POWER', name: 'U-Power', type: 'manufacturer' },
  { erpCode: 'PIQUERAS', name: 'Piqueras y Crespo', type: 'manufacturer' },
  { erpCode: 'AMOOS', name: 'Amoos', type: 'manufacturer' },
  { erpCode: 'DURABLE', name: 'Durable', type: 'manufacturer' },
  { erpCode: 'CASIO', name: 'Casio', type: 'manufacturer' },
  { erpCode: 'HP', name: 'HP', type: 'manufacturer' },
  { erpCode: 'SAFESCAN', name: 'Safescan', type: 'manufacturer' },
  { erpCode: 'VANTAGE', name: 'Vantage', type: 'distributor' },
  { erpCode: 'POST-IT', name: 'Post-it', type: 'manufacturer' },
  { erpCode: 'OXFORD', name: 'Oxford', type: 'manufacturer' },
  { erpCode: 'ARMOR', name: 'Armor', type: 'manufacturer' },
  { erpCode: 'LIDERPAPEL', name: 'Liderpapel', type: 'manufacturer' },
  { erpCode: 'DIST-001', name: 'Distrisantiago', type: 'distributor', baseImageUrl: 'https://www.distrisantiago.com/img/' },
]

/** Productos reales de jeyjo.es mapeados a la taxonomía del storefront */
export const JEYJO_PRODUCTS: JeyjoProductSeed[] = [
  // ── Escritura / bolígrafos ──────────────────────────────────────────
  {
    skuErp: '10102007',
    title: 'Bolígrafo BIC Cristal azul',
    slug: 'boligrafo-bic-cristal-azul',
    supplierErpCode: 'BIC',
    categorySlug: 'boligrafos',
    shortDescription: 'Bolígrafo BIC Cristal punta media 1,0 mm, tinta azul.',
    priceWithVat: 0.41,
    oemRef: '8373609',
    ean: '3086123363731',
    erpStock: 2400,
    facetColor: 'Azul',
    facetMaterial: 'Plástico',
    keywords: ['boligrafo', 'bic', 'cristal', 'azul'],
  },
  {
    skuErp: '10102010',
    title: 'Bolígrafo BIC Cristal rojo',
    slug: 'boligrafo-bic-cristal-rojo',
    supplierErpCode: 'BIC',
    categorySlug: 'boligrafos',
    shortDescription: 'Bolígrafo BIC Cristal punta media 1,0 mm, tinta roja.',
    priceWithVat: 0.41,
    oemRef: '8373619',
    erpStock: 1800,
    facetColor: 'Rojo',
    keywords: ['boligrafo', 'bic', 'cristal', 'rojo'],
  },
  {
    skuErp: '10102009',
    title: 'Bolígrafo BIC Cristal verde',
    slug: 'boligrafo-bic-cristal-verde',
    supplierErpCode: 'BIC',
    categorySlug: 'boligrafos',
    shortDescription: 'Bolígrafo BIC Cristal punta media 1,0 mm, tinta verde.',
    priceWithVat: 0.41,
    oemRef: '8373629',
    erpStock: 1200,
    facetColor: 'Verde',
    keywords: ['boligrafo', 'bic', 'cristal', 'verde'],
  },
  {
    skuErp: '10101171',
    title: 'Bolígrafo BIC Cristal UP surtido Fun',
    slug: 'boligrafo-bic-cristal-up-surtido',
    supplierErpCode: 'BIC',
    categorySlug: 'boligrafos',
    shortDescription: 'Bolígrafo BIC Cristal UP 1,2 mm en colores surtidos.',
    priceWithVat: 0.33,
    oemRef: '950446',
    erpStock: 960,
    facetColor: 'Surtido',
    keywords: ['boligrafo', 'bic', 'cristal', 'up', 'fun'],
  },
  {
    skuErp: '10102695',
    title: 'Bolígrafo Uni-Ball Jetstream retráctil 1,0 mm azul',
    slug: 'boligrafo-uni-ball-jetstream-azul',
    supplierErpCode: 'UNI-BALL',
    categorySlug: 'boligrafos',
    shortDescription: 'Roller gel retráctil Uni-Ball Jetstream, trazo 1,0 mm azul.',
    priceWithVat: 2.8,
    oemRef: '789107000',
    erpStock: 320,
    facetColor: 'Azul',
    keywords: ['boligrafo', 'roller', 'uni-ball', 'jetstream'],
  },
  // ── Escritura / rotuladores ─────────────────────────────────────────
  {
    skuErp: '10211089',
    title: 'Rotulador Uni-Ball Inkview marker azul',
    slug: 'rotulador-uni-ball-inkview-azul',
    supplierErpCode: 'UNI-BALL',
    categorySlug: 'rotuladores',
    shortDescription: 'Marcador de pizarra Uni-Ball Inkview punta cónica, tinta azul.',
    priceWithVat: 1.79,
    oemRef: '766873000',
    erpStock: 480,
    facetColor: 'Azul',
    keywords: ['marcador', 'pizarra', 'uni-ball', 'inkview'],
  },
  {
    skuErp: '10211090',
    title: 'Rotulador Uni-Ball Inkview marker negro',
    slug: 'rotulador-uni-ball-inkview-negro',
    supplierErpCode: 'UNI-BALL',
    categorySlug: 'rotuladores',
    shortDescription: 'Marcador de pizarra Uni-Ball Inkview punta cónica, tinta negra.',
    priceWithVat: 1.79,
    oemRef: '766865000',
    erpStock: 520,
    facetColor: 'Negro',
    keywords: ['marcador', 'pizarra', 'uni-ball', 'inkview'],
  },
  {
    skuErp: '10204016',
    title: 'Rotulador Staedtler Lumocolor 318 F verde',
    slug: 'rotulador-staedtler-lumocolor-318-verde',
    supplierErpCode: 'STAEDTLER',
    categorySlug: 'rotuladores',
    shortDescription: 'Rotulador permanente Staedtler Lumocolor 318 punta fina, verde.',
    priceWithVat: 1.67,
    oemRef: '318-5',
    erpStock: 280,
    facetColor: 'Verde',
    keywords: ['rotulador', 'permanente', 'staedtler', 'lumocolor'],
  },
  // ── Escritura / lápices y portaminas ────────────────────────────────
  {
    skuErp: '12501143',
    title: 'Portaminas Forofis Alfa 0,5 mm',
    slug: 'portaminas-forofis-alfa-05',
    supplierErpCode: 'FOROFIS',
    categorySlug: 'lapices',
    shortDescription: 'Portaminas metálico Forofis Alfa, mina 0,5 mm.',
    priceWithVat: 0.47,
    oemRef: '91561',
    erpStock: 640,
    facetMaterial: 'Metal',
    keywords: ['portaminas', 'forofis', 'alfa'],
  },
  {
    skuErp: '21901181',
    title: 'Minas Forofis 0,5 HB (tubo de 12)',
    slug: 'minas-forofis-05-hb',
    supplierErpCode: 'FOROFIS',
    categorySlug: 'lapices',
    shortDescription: 'Minas de grafito HB 0,5 mm, tubo de 12 unidades.',
    priceWithVat: 0.23,
    oemRef: '91570',
    erpStock: 1200,
    keywords: ['minas', 'grafito', 'forofis', 'hb'],
  },
  // ── Escritura / corrección ──────────────────────────────────────────
  {
    skuErp: '15103019',
    title: 'Corrector líquido Paper Mate NP10 punta metal',
    slug: 'corrector-liquido-paper-mate-np10',
    supplierErpCode: 'BIC',
    categorySlug: 'correccion',
    shortDescription: 'Corrector líquido en bolígrafo Paper Mate NP10 con punta metálica.',
    priceWithVat: 1.98,
    oemRef: '2037841',
    erpStock: 180,
    keywords: ['corrector', 'liquido', 'paper mate'],
  },
  // ── Papel / folios ──────────────────────────────────────────────────
  {
    skuErp: '12701009',
    title: 'Papel A4 Navigator 80 g 500 hojas universal',
    slug: 'papel-a4-navigator-80g-500h',
    supplierErpCode: 'NAVIGATOR',
    categorySlug: 'folios',
    shortDescription: 'Papel multifunción blanco A4 80 g/m², paquete de 500 hojas.',
    priceWithVat: 6.39,
    oemRef: 'NAVIGATOR A4 80G',
    ean: '5602024001480',
    erpStock: 480,
    facetColor: 'Blanco',
    facetMaterial: 'Papel',
    keywords: ['papel', 'navigator', 'a4', '80g', 'folios'],
  },
  {
    skuErp: '12701208',
    title: 'Papel color A4 Colore 80 500 hojas naranja',
    slug: 'papel-color-a4-colore-80-naranja',
    supplierErpCode: 'LIDERPAPEL',
    categorySlug: 'folios',
    shortDescription: 'Papel de color A4 80 g/m², 500 hojas color naranja (aragosta).',
    priceWithVat: 14.78,
    oemRef: '74421297',
    erpStock: 96,
    facetColor: 'Naranja',
    keywords: ['papel', 'color', 'a4', 'naranja', 'colore'],
  },
  {
    skuErp: '12701213',
    title: 'Papel color A4 Colore 80 500 hojas verde',
    slug: 'papel-color-a4-colore-80-verde',
    supplierErpCode: 'LIDERPAPEL',
    categorySlug: 'folios',
    shortDescription: 'Papel de color A4 80 g/m², 500 hojas color verde.',
    priceWithVat: 14.78,
    oemRef: '74121297',
    erpStock: 84,
    facetColor: 'Verde',
    keywords: ['papel', 'color', 'a4', 'verde', 'colore'],
  },
  // ── Papel / cuadernos ───────────────────────────────────────────────
  {
    skuErp: '26901018',
    title: 'Taco banderitas adhesivas Post-it naranja',
    slug: 'banderitas-post-it-naranja',
    supplierErpCode: 'POST-IT',
    categorySlug: 'cuadernos',
    shortDescription: 'Banderitas índice adhesivas Post-it 680 (1"), color naranja.',
    priceWithVat: 3.78,
    oemRef: '680-4',
    erpStock: 220,
    facetColor: 'Naranja',
    keywords: ['post-it', 'banderitas', 'adhesivas', 'naranja'],
  },
  // ── Papel / manualidades ────────────────────────────────────────────
  {
    skuErp: '23101401',
    title: 'Líquido activador Supertite Slime 260 ml',
    slug: 'liquido-activador-supertite-slime',
    supplierErpCode: 'LIDERPAPEL',
    categorySlug: 'manualidades',
    shortDescription: 'Líquido activador para manualidades Supertite Slime, 260 ml.',
    priceWithVat: 2.76,
    oemRef: '2792',
    erpStock: 140,
    keywords: ['slime', 'manualidades', 'supertite', 'escolar'],
  },
  // ── Papel / sobres ──────────────────────────────────────────────────
  {
    skuErp: '26401138',
    title: 'Sobre bolsa burbuja nº14 (ref. 4) paquete 100',
    slug: 'sobre-bolsa-burbuja-n14-p100',
    supplierErpCode: 'VANTAGE',
    categorySlug: 'sobres',
    shortDescription: 'Sobres bolsa burbuja nº14, 180×265 mm, caja de 100 unidades.',
    priceWithVat: 37.98,
    oemRef: 'GRANEL 14',
    erpStock: 48,
    facetMaterial: 'Papel burbuja',
    keywords: ['sobre', 'burbuja', 'embalaje', 'envio'],
  },
  {
    skuErp: '11403013',
    title: 'Bolsa auto-cierre Minigrip 150×180 mm paquete 100',
    slug: 'bolsa-minigrip-150x180-p100',
    supplierErpCode: 'VANTAGE',
    categorySlug: 'sobres',
    shortDescription: 'Bolsas auto-cierre Minigrip neutras 150×180 mm, paquete de 100.',
    priceWithVat: 4.97,
    oemRef: '1420150180',
    erpStock: 360,
    keywords: ['bolsa', 'minigrip', 'embalaje'],
  },
  // ── Impresión / tóner ───────────────────────────────────────────────
  {
    skuErp: 'ERP-TNR-085',
    title: 'Tóner negro HP 85A',
    slug: 'toner-negro-hp-85a',
    supplierErpCode: 'HP',
    categorySlug: 'toner',
    shortDescription: 'Cartucho de tóner negro compatible HP LaserJet Pro.',
    priceWithVat: 51.43,
    oemRef: 'CE285A',
    ean: '0886112750001',
    erpStock: 80,
    facetColor: 'Negro',
    facetMaterial: 'Polímero',
    keywords: ['toner', 'hp', '85a', 'negro', 'laser'],
  },
  // ── Impresión / impresoras ──────────────────────────────────────────
  {
    skuErp: 'ERP-PRT-M404',
    title: 'Impresora láser HP Pro M404',
    slug: 'impresora-laser-hp-pro-m404',
    supplierErpCode: 'HP',
    categorySlug: 'impresoras',
    shortDescription: 'Impresora láser monocromo A4 para oficina.',
    priceWithVat: 228.69,
    oemRef: 'W1A52A',
    ean: '0886112750100',
    erpStock: 15,
    facetColor: 'Blanco',
    facetMaterial: 'Plástico',
    keywords: ['impresora', 'laser', 'hp', 'm404'],
  },
  // ── Impresión / etiquetas ───────────────────────────────────────────
  {
    skuErp: '16103024',
    title: 'Cinta rotuladora DYMO LM D1 7 m 12 mm negro sobre rojo',
    slug: 'cinta-dymo-lm-d1-negro-rojo',
    supplierErpCode: 'DYMO',
    categorySlug: 'etiquetas',
    shortDescription: 'Cinta de rotular DYMO LM D1, 7 m × 12 mm, negro sobre rojo.',
    priceWithVat: 22.29,
    oemRef: 'S0720570',
    erpStock: 120,
    facetColor: 'Negro/Rojo',
    keywords: ['cinta', 'dymo', 'rotular', 'etiquetado'],
  },
  {
    skuErp: '16103080',
    title: 'Cinta rotuladora DYMO LetraTag plástico negro sobre transparente',
    slug: 'cinta-dymo-letratag-negro-transparente',
    supplierErpCode: 'DYMO',
    categorySlug: 'etiquetas',
    shortDescription: 'Cinta LetraTag plástico 4 m × 12 mm, negro sobre transparente.',
    priceWithVat: 9.72,
    oemRef: 'S0721530',
    erpStock: 200,
    keywords: ['cinta', 'dymo', 'letratag', 'etiquetado'],
  },
  {
    skuErp: '18801185',
    title: 'Etiquetas DYMO LabelWriter 19×51 mm rollo 500',
    slug: 'etiquetas-dymo-labelwriter-19x51',
    supplierErpCode: 'DYMO',
    categorySlug: 'etiquetas',
    shortDescription: 'Etiquetas DYMO LabelWriter 19×51 mm, rollo de 500 uds. papel blanco.',
    priceWithVat: 16.63,
    oemRef: 'S0722550',
    erpStock: 88,
    keywords: ['etiquetas', 'dymo', 'labelwriter'],
  },
  // ── Archivo / archivadores ──────────────────────────────────────────
  {
    skuErp: '11601380',
    title: 'Archivador Olef color A4 75 mm blanco',
    slug: 'archivador-olef-color-a4-75-blanco',
    supplierErpCode: 'OLEF',
    categorySlug: 'archivadores',
    shortDescription: 'Archivador de palanca Olef plastificado color A4, lomo 75 mm, blanco.',
    priceWithVat: 3.37,
    oemRef: 'OL2070B',
    erpStock: 420,
    facetColor: 'Blanco',
    facetMaterial: 'Cartón plastificado',
    keywords: ['archivador', 'olef', 'palanca', 'a4', 'blanco'],
  },
  {
    skuErp: '11601364',
    title: 'Archivador Olef color folio 75 mm azul',
    slug: 'archivador-olef-color-fo-75-azul',
    supplierErpCode: 'OLEF',
    categorySlug: 'archivadores',
    shortDescription: 'Archivador de palanca Olef plastificado color folio, lomo 75 mm, azul.',
    priceWithVat: 3.37,
    oemRef: 'OL2071AZ',
    erpStock: 380,
    facetColor: 'Azul',
    keywords: ['archivador', 'olef', 'palanca', 'folio', 'azul'],
  },
  {
    skuErp: '11601231',
    title: 'Archivador Esselte plástico forrado con rado A4 75 mm azul',
    slug: 'archivador-esselte-plas-forrado-a4-75-azul',
    supplierErpCode: 'ESSELTE',
    categorySlug: 'archivadores',
    shortDescription: 'Archivador de palanca Esselte plástico forrado con rado A4, lomo 75 mm.',
    priceWithVat: 3.97,
    oemRef: '42311',
    erpStock: 260,
    facetColor: 'Azul',
    keywords: ['archivador', 'esselte', 'palanca', 'a4'],
  },
  {
    skuErp: '11601929',
    title: 'Archivador Unisystem clásico cartón rado A4 65 mm azul',
    slug: 'archivador-unisystem-clasico-a4-65-azul',
    supplierErpCode: 'ESSELTE',
    categorySlug: 'archivadores',
    shortDescription: 'Archivador de palanca Unisystem cartón forrado rado A4, lomo 65 mm.',
    priceWithVat: 4.62,
    oemRef: '092453',
    erpStock: 310,
    facetColor: 'Azul',
    keywords: ['archivador', 'unisystem', 'carton', 'a4'],
  },
  // ── Archivo / carpetas ──────────────────────────────────────────────
  {
    skuErp: '10404736',
    title: 'Carpeta canguro Esselte PVC básica A4 4 anillas 50 mm',
    slug: 'carpeta-canguro-esselte-a4-4-anillas-50',
    supplierErpCode: 'ESSELTE',
    categorySlug: 'carpetas',
    shortDescription: 'Carpeta canguro Esselte PVC básica A4 con 4 anillas mixtas, lomo 50 mm.',
    priceWithVat: 7.81,
    oemRef: '49705',
    erpStock: 180,
    facetColor: 'Blanco',
    keywords: ['carpeta', 'canguro', 'esselte', 'anillas'],
  },
  {
    skuErp: '16201496',
    title: 'Funda distintivo Durable doble 54×85 mm pack 10',
    slug: 'funda-distintivo-durable-doble-54x85',
    supplierErpCode: 'DURABLE',
    categorySlug: 'carpetas',
    shortDescription: 'Fundas de identificación Durable doble 54×85 mm, pack de 10 transparentes.',
    priceWithVat: 36.49,
    oemRef: '891919',
    erpStock: 64,
    facetMaterial: 'PVC',
    keywords: ['funda', 'distintivo', 'durable', 'portacarnet'],
  },
  // ── Archivo / separadores ─────────────────────────────────────────────
  {
    skuErp: '10409040',
    title: 'Subcarpeta Gio Pocket 320 g folio verde paquete 25',
    slug: 'subcarpeta-gio-pocket-320g-fo-verde-p25',
    supplierErpCode: 'ESSELTE',
    categorySlug: 'separadores',
    shortDescription: 'Subcarpeta Gio Pocket 320 g/m² folio, color verde, paquete de 25.',
    priceWithVat: 23.39,
    oemRef: '400040685',
    erpStock: 72,
    facetColor: 'Verde',
    keywords: ['subcarpeta', 'gio', 'pocket', 'folio'],
  },
  {
    skuErp: '20401036',
    title: 'Índice Esselte PP alfabético folio 20 pestañas gris',
    slug: 'indice-esselte-pp-alfabetico-fo-20-gris',
    supplierErpCode: 'ESSELTE',
    categorySlug: 'separadores',
    shortDescription: 'Índice alfabético Esselte PP folio, 20 pestañas, 16 taladros, gris.',
    priceWithVat: 7.9,
    oemRef: '47138',
    erpStock: 140,
    facetColor: 'Gris',
    keywords: ['indice', 'alfabetico', 'esselte', 'separadores'],
  },
  // ── Oficina / grapado ───────────────────────────────────────────────
  {
    skuErp: '12901446',
    title: 'Grapadora Rapesco antibacteriana Sting Ray (20 hojas)',
    slug: 'grapadora-rapesco-sting-ray-20h',
    supplierErpCode: 'RAPID',
    categorySlug: 'grapado',
    shortDescription: 'Grapadora Rapesco Sting Ray antibacteriana, grapa hasta 20 hojas, incluye 1000 grapas.',
    priceWithVat: 6.48,
    oemRef: '1482',
    erpStock: 96,
    facetColor: 'Negro',
    keywords: ['grapadora', 'rapesco', 'sting ray'],
  },
  {
    skuErp: '12901162',
    title: 'Grapadora Petrus 226 azul',
    slug: 'grapadora-petrus-226-azul',
    supplierErpCode: 'PETRUS',
    categorySlug: 'grapado',
    shortDescription: 'Grapadora de sobremesa Petrus 226, cuerpo metálico azul.',
    priceWithVat: 33.25,
    oemRef: '44794',
    erpStock: 48,
    facetColor: 'Azul',
    facetMaterial: 'Metal',
    keywords: ['grapadora', 'petrus', '226', 'sobremesa'],
  },
  {
    skuErp: '12901056',
    title: 'Grapadora tenaza Rapid K1 (50 hojas)',
    slug: 'grapadora-tenaza-rapid-k1-50h',
    supplierErpCode: 'RAPID',
    categorySlug: 'grapado',
    shortDescription: 'Grapadora tenaza Rapid K1 de gran capacidad, grapa hasta 50 hojas.',
    priceWithVat: 38.52,
    oemRef: '10510601',
    erpStock: 36,
    keywords: ['grapadora', 'tenaza', 'rapid', 'k1'],
  },
  {
    skuErp: '12901127',
    title: 'Grapadora eléctrica Petrus E-120 negro (20 hojas)',
    slug: 'grapadora-electrica-petrus-e120',
    supplierErpCode: 'PETRUS',
    categorySlug: 'grapado',
    shortDescription: 'Grapadora eléctrica Petrus E-120, grapa hasta 20 hojas, adaptador incluido.',
    priceWithVat: 161.94,
    oemRef: '623385',
    erpStock: 12,
    facetColor: 'Negro',
    keywords: ['grapadora', 'electrica', 'petrus', 'e-120'],
  },
  // ── Oficina / corte ─────────────────────────────────────────────────
  {
    skuErp: '27601170',
    title: 'Tijera Dahle Titanium 14 cm',
    slug: 'tijera-dahle-titanium-14cm',
    supplierErpCode: 'DAHLE',
    categorySlug: 'corte',
    shortDescription: 'Tijeras Dahle Titanium de 14 cm, hojas de acero inoxidable.',
    priceWithVat: 8.77,
    oemRef: '54305-12977',
    erpStock: 120,
    facetMaterial: 'Acero inoxidable',
    keywords: ['tijeras', 'dahle', 'titanium'],
  },
  {
    skuErp: '27601209',
    title: 'Tijeras Forofis oficina 25 cm',
    slug: 'tijeras-forofis-oficina-25cm',
    supplierErpCode: 'FOROFIS',
    categorySlug: 'corte',
    shortDescription: 'Tijeras de oficina Forofis de 25 cm.',
    priceWithVat: 3.12,
    oemRef: '91117',
    erpStock: 200,
    keywords: ['tijeras', 'forofis', 'oficina'],
  },
  {
    skuErp: '11701064',
    title: 'Cizalla de palanca Vantage 10 A4',
    slug: 'cizalla-palanca-vantage-10-a4',
    supplierErpCode: 'VANTAGE',
    categorySlug: 'corte',
    shortDescription: 'Cizalla de palanca Vantage 10 para formato A4.',
    priceWithVat: 22.49,
    oemRef: '40010-20057',
    erpStock: 28,
    keywords: ['cizalla', 'palanca', 'vantage', 'a4'],
  },
  {
    skuErp: '11702050',
    title: 'Cizalla de rodillo Fellowes Electron A3',
    slug: 'cizalla-rodillo-fellowes-electron-a3',
    supplierErpCode: 'FELLOWES',
    categorySlug: 'corte',
    shortDescription: 'Cizalla de rodillo Fellowes Electron para formato A3.',
    priceWithVat: 98.83,
    oemRef: '5410501',
    erpStock: 8,
    keywords: ['cizalla', 'rodillo', 'fellowes', 'a3'],
  },
  // ── Oficina / calculadoras ──────────────────────────────────────────
  {
    skuErp: 'CASIO-FX85',
    title: 'Calculadora científica Casio FX-85 SP CW',
    slug: 'calculadora-casio-fx-85-sp-cw',
    supplierErpCode: 'CASIO',
    categorySlug: 'calculadoras',
    shortDescription: 'Calculadora científica Casio FX-85 SP CW ClassWiz, 300 funciones, solar.',
    priceWithVat: 28.92,
    oemRef: 'FX-85SPCW',
    ean: '4549526612220',
    erpStock: 84,
    facetColor: 'Negro',
    keywords: ['calculadora', 'cientifica', 'casio', 'fx-85', 'classwiz'],
  },
  {
    skuErp: '23201030',
    title: 'Báscula digital DYMO M5 Mailing 5 kg',
    slug: 'bascula-digital-dymo-m5-mailing',
    supplierErpCode: 'DYMO',
    categorySlug: 'calculadoras',
    shortDescription: 'Báscula digital DYMO M5 Mailing, capacidad 5 kg para envíos.',
    priceWithVat: 73.97,
    oemRef: 'S0929000',
    erpStock: 24,
    keywords: ['bascula', 'dymo', 'mailing', 'envio'],
  },
  // ── Oficina / adhesivos ─────────────────────────────────────────────
  {
    skuErp: '23103008',
    title: 'Pegamento instantáneo Super Glue-3 3 g',
    slug: 'pegamento-instantaneo-super-glue-3',
    supplierErpCode: 'LIDERPAPEL',
    categorySlug: 'adhesivos',
    shortDescription: 'Adhesivo instantáneo (cianocrilato) Super Glue-3, 3 g.',
    priceWithVat: 3.67,
    oemRef: '2971815',
    erpStock: 320,
    keywords: ['pegamento', 'instantaneo', 'super glue'],
  },
  {
    skuErp: '11102019',
    title: 'Gomas elásticas bolsa 1 kg 100 mm nº10',
    slug: 'gomas-elasticas-bolsa-1kg-100mm',
    supplierErpCode: 'VANTAGE',
    categorySlug: 'adhesivos',
    shortDescription: 'Gomas elásticas en bolsa de 1 kg, 100 mm (nº10).',
    priceWithVat: 12.37,
    oemRef: 'GO1000BA100',
    erpStock: 160,
    keywords: ['gomas', 'elasticas', 'embalaje'],
  },
  // ── Oficina / maquinaria (destructoras) ─────────────────────────────
  {
    skuErp: '16401136',
    title: 'Destructora Fellowes P-25S (5 hojas tiras)',
    slug: 'destructora-fellowes-p-25s',
    supplierErpCode: 'FELLOWES',
    categorySlug: 'grapado',
    shortDescription: 'Destructora de papel Fellowes P-25S, corte en tiras, 5 hojas.',
    priceWithVat: 45.29,
    oemRef: '4701001',
    erpStock: 18,
    keywords: ['destructora', 'fellowes', 'p-25s', 'oficina'],
  },
  {
    skuErp: '16401399',
    title: 'Destructora Rexel Promax QS RSX1035 (10 hojas partículas)',
    slug: 'destructora-rexel-promax-rsx1035',
    supplierErpCode: 'REXEL',
    categorySlug: 'grapado',
    shortDescription: 'Destructora Rexel Promax QS RSX1035, corte en partículas, 10 hojas.',
    priceWithVat: 288.59,
    oemRef: '2104585EU',
    erpStock: 6,
    keywords: ['destructora', 'rexel', 'promax', 'rsx1035'],
  },
  {
    skuErp: '16401295',
    title: 'Destructora Rexel Promax RSX1538 (15 hojas partículas)',
    slug: 'destructora-rexel-promax-rsx1538',
    supplierErpCode: 'REXEL',
    categorySlug: 'grapado',
    shortDescription: 'Destructora Rexel Promax RSX1538, corte en partículas, 15 hojas.',
    priceWithVat: 742.34,
    oemRef: '2104587EU',
    erpStock: 3,
    keywords: ['destructora', 'rexel', 'promax', 'rsx1538'],
  },
  // ── Oficina / presentación ──────────────────────────────────────────
  {
    skuErp: '23801771',
    title: 'Pizarra blanca magnética Nobo Premium Plus 150×120 cm',
    slug: 'pizarra-blanca-magnetica-nobo-150x120',
    supplierErpCode: 'NOBO',
    categorySlug: 'calculadoras',
    shortDescription: 'Pizarra blanca magnética Nobo Premium Plus lacada, marco aluminio 150×120 cm.',
    priceWithVat: 203.55,
    oemRef: '1915159',
    erpStock: 8,
    facetMaterial: 'Lacado',
    keywords: ['pizarra', 'blanca', 'magnetica', 'nobo'],
  },
  {
    skuErp: '23801451',
    title: 'Vitrina Nobo exterior blanca magnética 6 hojas A4',
    slug: 'vitrina-nobo-exterior-blanca-6h-a4',
    supplierErpCode: 'NOBO',
    categorySlug: 'calculadoras',
    shortDescription: 'Vitrina de exterior Nobo blanca magnética para 6 hojas A4.',
    priceWithVat: 306.43,
    oemRef: '1902578',
    erpStock: 4,
    keywords: ['vitrina', 'nobo', 'exterior', 'magnetica'],
  },
  {
    skuErp: '24404369',
    title: 'Imanes Nobo bolsa 10 uds. 32 mm transparentes',
    slug: 'imanes-nobo-bolsa-10-32mm',
    supplierErpCode: 'NOBO',
    categorySlug: 'calculadoras',
    shortDescription: 'Imanes para pizarras de cristal Nobo, bolsa de 10 uds. 32 mm transparentes.',
    priceWithVat: 31.56,
    oemRef: '1903854',
    erpStock: 56,
    keywords: ['imanes', 'nobo', 'pizarra'],
  },
  // ── Oficina / ergonomía ─────────────────────────────────────────────
  {
    skuErp: '42105111',
    title: 'Soporte portátil Fellowes Office Suites',
    slug: 'soporte-portatil-fellowes-office-suites',
    supplierErpCode: 'FELLOWES',
    categorySlug: 'calculadoras',
    shortDescription: 'Soporte ergonómico para portátil Fellowes Office Suites, color azul.',
    priceWithVat: 51.03,
    oemRef: '8032001',
    erpStock: 32,
    facetColor: 'Azul',
    keywords: ['soporte', 'portatil', 'fellowes', 'ergonomia'],
  },
  {
    skuErp: '42101282',
    title: 'Soporte monitor Fellowes Platinum doble brazo blanco',
    slug: 'soporte-monitor-fellowes-platinum-doble',
    supplierErpCode: 'FELLOWES',
    categorySlug: 'calculadoras',
    shortDescription: 'Soporte de brazo doble para monitor Fellowes Platinum Series, blanco.',
    priceWithVat: 268.31,
    oemRef: '8056301',
    erpStock: 6,
    facetColor: 'Blanco',
    keywords: ['soporte', 'monitor', 'fellowes', 'ergonomia'],
  },
  // ── Mobiliario / sillas (mapeado a oficina) ─────────────────────────
  {
    skuErp: '24404589',
    title: 'Silla Piqueras Esteras dirección negra',
    slug: 'silla-piqueras-esteras-direccion-negra',
    supplierErpCode: 'PIQUERAS',
    categorySlug: 'calculadoras',
    shortDescription: 'Silla de dirección Piqueras Esteras, respaldo en malla, color negro.',
    priceWithVat: 149.41,
    oemRef: '32DBD840',
    erpStock: 10,
    facetColor: 'Negro',
    facetMaterial: 'Malla',
    keywords: ['silla', 'direccion', 'piqueras', 'esteras', 'ergonomica'],
  },
  {
    skuErp: '24405093',
    title: 'Silla Piqueras Gontar malla azul',
    slug: 'silla-piqueras-gontar-malla-azul',
    supplierErpCode: 'PIQUERAS',
    categorySlug: 'calculadoras',
    shortDescription: 'Silla operativa Piqueras Gontar con respaldo de malla, color azul.',
    priceWithVat: 134.23,
    oemRef: '31BM8403D229CRRP',
    erpStock: 14,
    facetColor: 'Azul',
    keywords: ['silla', 'operativa', 'piqueras', 'gontar'],
  },
  // ── Reciclaje / limpieza ──────────────────────────────────────────────
  {
    skuErp: '18701089',
    title: 'Papel higiénico Amoos Professional plegado 2 capas paquete 250',
    slug: 'papel-higienico-amoos-professional-250',
    supplierErpCode: 'AMOOS',
    categorySlug: 'limpieza',
    shortDescription: 'Papel higiénico Amoos Professional plegado 2 capas, 21×11 cm, 250 servicios.',
    priceWithVat: 1.37,
    oemRef: 'N621101',
    erpStock: 800,
    facetColor: 'Blanco',
    keywords: ['papel', 'higienico', 'amoos', 'celulosa'],
  },
  {
    skuErp: '90001009',
    title: 'Toallitas Pharmia Baby paquete 60',
    slug: 'toallitas-pharmia-baby-p60',
    supplierErpCode: 'AMOOS',
    categorySlug: 'limpieza',
    shortDescription: 'Toallitas húmedas Pharmia Baby, paquete de 60 unidades.',
    priceWithVat: 2.82,
    oemRef: '60065',
    erpStock: 240,
    keywords: ['toallitas', 'pharmia', 'baby', 'higiene'],
  },
  {
    skuErp: '15203896',
    title: 'Guante desechable nitrilo GD21 azul talla XL caja 100',
    slug: 'guante-nitrilo-gd21-azul-xl-c100',
    supplierErpCode: 'U-POWER',
    categorySlug: 'limpieza',
    shortDescription: 'Guantes desechables de nitrilo Santex GD21 azul, talla XL, caja de 100.',
    priceWithVat: 5.73,
    oemRef: 'GD21BE',
    erpStock: 180,
    facetColor: 'Azul',
    facetMaterial: 'Nitrilo',
    keywords: ['guantes', 'nitrilo', 'proteccion', 'desechable'],
  },
  {
    skuErp: '15202811',
    title: 'Zapato de seguridad U-Power Logan talla 41',
    slug: 'zapato-seguridad-u-power-logan-t41',
    supplierErpCode: 'U-POWER',
    categorySlug: 'limpieza',
    shortDescription: 'Zapato de seguridad U-Power Logan, talla 41.',
    priceWithVat: 108.41,
    oemRef: 'RV20104 41',
    erpStock: 12,
    facetColor: 'Negro',
    keywords: ['zapato', 'seguridad', 'u-power', 'logan', 'epi'],
  },
  {
    skuErp: '15202909',
    title: 'Pantalón U-Power Guapo elástico talla 2XL negro',
    slug: 'pantalon-u-power-guapo-2xl-negro',
    supplierErpCode: 'U-POWER',
    categorySlug: 'limpieza',
    shortDescription: 'Pantalón de trabajo U-Power Guapo con cintura elástica, talla 2XL negro.',
    priceWithVat: 34.64,
    oemRef: 'WST211BC 2XL',
    erpStock: 28,
    facetColor: 'Negro',
    keywords: ['pantalon', 'trabajo', 'u-power', 'guapo', 'epi'],
  },
  // ── Control acceso ────────────────────────────────────────────────────
  {
    skuErp: '45003119',
    title: 'Control de acceso Safescan TimeMoto TM-626',
    slug: 'control-acceso-safescan-timemoto-tm626',
    supplierErpCode: 'SAFESCAN',
    categorySlug: 'calculadoras',
    shortDescription: 'Terminal de control horario Safescan TimeMoto TM-626.',
    priceWithVat: 480.06,
    oemRef: '125-0586',
    erpStock: 0,
    keywords: ['control', 'acceso', 'timemoto', 'safescan', 'horario'],
  },
  {
    skuErp: '45011239',
    title: 'Contador de billetes Safescan 2210',
    slug: 'contador-billetes-safescan-2210',
    supplierErpCode: 'SAFESCAN',
    categorySlug: 'calculadoras',
    shortDescription: 'Contador de billetes Safescan 2210 con detector UV y por tamaño.',
    priceWithVat: 257.49,
    oemRef: '115-0708',
    erpStock: 4,
    keywords: ['contador', 'billetes', 'safescan'],
  },
  // ── Libros de texto (vuelta al cole) ──────────────────────────────────
  {
    skuErp: '9789925309139',
    title: 'OPTIONS 4 ESO Ejercicios',
    slug: 'options-4-eso-ejercicios',
    supplierErpCode: 'OXFORD',
    categorySlug: 'cuadernos',
    shortDescription: 'Libro de ejercicios OPTIONS 4 ESO.',
    priceWithVat: 30.84,
    oemRef: '9789925309139',
    erpStock: 45,
    keywords: ['libro', 'texto', 'eso', 'options', 'vuelta al cole'],
  },
  {
    skuErp: '9788468214702',
    title: 'EP 5 Matemáticas cuaderno Aula Activa Vicens',
    slug: 'ep-5-matematicas-aula-activa-vicens',
    supplierErpCode: 'OXFORD',
    categorySlug: 'cuadernos',
    shortDescription: 'Cuaderno EP 5 Matemáticas Aula Activa, editorial Vicens Vives (T25).',
    priceWithVat: 18.38,
    oemRef: '9788468214702',
    erpStock: 60,
    keywords: ['libro', 'texto', 'matematicas', 'primaria', 'vicens'],
  },
  {
    skuErp: '9780230476332',
    title: 'EP Tiger Team 4 Macmillan',
    slug: 'ep-tiger-team-4-macmillan',
    supplierErpCode: 'OXFORD',
    categorySlug: 'cuadernos',
    shortDescription: 'Libro de inglés EP Tiger Team 4, editorial Macmillan (T25).',
    priceWithVat: 27.26,
    oemRef: '9780230476332',
    erpStock: 38,
    keywords: ['libro', 'texto', 'ingles', 'tiger team', 'macmillan'],
  },
]

/** Productos alineados al stub ERP (`packages/erp-ports`) */
export const JEYJO_ERP_STUB_PRODUCTS: JeyjoProductSeed[] = [
  {
    skuErp: 'ERP-GRF-001',
    title: 'Grifo monomando cromado 35mm',
    slug: 'grifo-monomando-cromado-35mm',
    supplierErpCode: 'DIST-001',
    categorySlug: 'boligrafos',
    shortDescription: 'Grifo monomando para lavabo, acabado cromado.',
    priceWithVat: 55.54,
    erpStock: 120,
    mainWholesaleRef: 'DS-12345',
    oemRef: 'GRF-35-CR',
    facetColor: 'Cromado',
    facetMaterial: 'Metal',
    keywords: ['grifo', 'fontaneria'],
  },
  {
    skuErp: 'ERP-PVC-032',
    title: 'Manguito PVC 32mm',
    slug: 'manguito-pvc-32mm',
    supplierErpCode: 'DIST-001',
    categorySlug: 'adhesivos',
    shortDescription: 'Manguito de unión PVC diámetro 32mm.',
    priceWithVat: 1.45,
    erpStock: 500,
    facetColor: 'Blanco',
    facetMaterial: 'PVC',
    ecoLabel: true,
    keywords: ['manguito', 'pvc', 'fontaneria'],
  },
]

/** Fixtures de pruebas CA-PRECIOS / CA-B2B (se mantienen para tests automatizados) */
export const JEYJO_REF_FIXTURES: JeyjoProductSeed[] = [
  {
    skuErp: 'REF-001',
    title: 'Fixture CA-PRECIOS-001',
    slug: 'ref-001',
    supplierErpCode: 'DIST-001',
    categorySlug: 'boligrafos',
    shortDescription: 'Producto fixture CA-PRECIOS-001.',
    priceWithVat: 1.21,
    erpStock: 100,
    mainWholesaleRef: 'WH-REF-001',
    facetColor: 'Azul',
    facetMaterial: 'Plástico',
  },
  {
    skuErp: 'REF-002',
    title: 'Fixture CA-PRECIOS-002',
    slug: 'ref-002',
    supplierErpCode: 'DIST-001',
    categorySlug: 'boligrafos',
    shortDescription: 'Producto fixture CA-PRECIOS-002.',
    priceWithVat: 14.52,
    erpStock: 2,
    mainWholesaleRef: 'WH-REF-002',
    facetColor: 'Negro',
    facetMaterial: 'Plástico',
  },
  {
    skuErp: 'REF-003',
    title: 'Fixture CA-PRECIOS-003',
    slug: 'ref-003',
    supplierErpCode: 'DIST-001',
    categorySlug: 'boligrafos',
    shortDescription: 'Producto fixture CA-PRECIOS-003 (oferta grupo).',
    priceWithVat: 14.52,
    erpStock: 0,
    mainWholesaleRef: 'WH-REF-003',
    facetColor: 'Negro',
    facetMaterial: 'Metal',
    ecoLabel: true,
  },
  {
    skuErp: 'REF-004',
    title: 'Fixture CA-PRECIOS-004',
    slug: 'ref-004',
    supplierErpCode: 'DIST-001',
    categorySlug: 'boligrafos',
    shortDescription: 'Producto fixture CA-PRECIOS-004 (precio especial).',
    priceWithVat: 12.1,
    erpStock: 20,
    facetColor: 'Negro',
    facetMaterial: 'Metal',
  },
  {
    skuErp: 'REF-010',
    title: 'Fixture CA-B2B-004',
    slug: 'ref-010',
    supplierErpCode: 'DIST-001',
    categorySlug: 'boligrafos',
    shortDescription: 'Producto fixture historial de compras (REF-010).',
    priceWithVat: 8.47,
    erpStock: 30,
    mainWholesaleRef: 'WH-REF-010',
    facetColor: 'Negro',
    facetMaterial: 'Metal',
  },
]

export function priceWithoutVat(priceWithVat: number, vatRate = 21): number {
  return Math.round((priceWithVat / (1 + vatRate / 100)) * 100) / 100
}

export function b2bPrice(p1: number): number {
  return Math.round(p1 * 0.87 * 100) / 100
}
