/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    suppliers: Supplier;
    media: Media;
    quotes: Quote;
    'rma-incidents': RmaIncident;
    coupons: Coupon;
    'b2b-catalog-downloads': B2BCatalogDownload;
    'customer-documents': CustomerDocument;
    'special-prices': SpecialPrice;
    'group-offers': GroupOffer;
    addresses: Address;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'rma-incidents': RmaIncidentsSelect<false> | RmaIncidentsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'b2b-catalog-downloads': B2BCatalogDownloadsSelect<false> | B2BCatalogDownloadsSelect<true>;
    'customer-documents': CustomerDocumentsSelect<false> | CustomerDocumentsSelect<true>;
    'special-prices': SpecialPricesSelect<false> | SpecialPricesSelect<true>;
    'group-offers': GroupOffersSelect<false> | GroupOffersSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    systemSettings: SystemSetting;
    paymentSettings: PaymentSetting;
    marketingSettings: MarketingSetting;
    newsletterSettings: NewsletterSetting;
    skaiSettings: SkaiSetting;
    analyticsSettings: AnalyticsSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    systemSettings: SystemSettingsSelect<false> | SystemSettingsSelect<true>;
    paymentSettings: PaymentSettingsSelect<false> | PaymentSettingsSelect<true>;
    marketingSettings: MarketingSettingsSelect<false> | MarketingSettingsSelect<true>;
    newsletterSettings: NewsletterSettingsSelect<false> | NewsletterSettingsSelect<true>;
    skaiSettings: SkaiSettingsSelect<false> | SkaiSettingsSelect<true>;
    analyticsSettings: AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Al menos un rol staff es necesario para acceder al backoffice.
   */
  staffRoles?:
    | ('superadmin' | 'administracion' | 'catalogo' | 'personalizacion' | 'mantenimiento' | 'marketing')[]
    | null;
  twoFactorEnabled?: boolean | null;
  totpSecret?: string | null;
  /**
   * Legacy template — usar staffRoles para backoffice.
   */
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bandeja operativa OMS: /admin/oms
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  origin?: ('b2c' | 'b2b' | 'eva') | null;
  jeyjoStatus?:
    | (
        | 'pending'
        | 'pending_payment'
        | 'pending_company_approval'
        | 'pending_confirmation'
        | 'confirmed'
        | 'preparing'
        | 'shipped'
        | 'delivered'
        | 'cancelled'
      )
    | null;
  /**
   * UUID de public.customers hasta enlace formal en #16
   */
  customerRef?: string | null;
  /**
   * web_profiles.id del subusuario que envió el pedido
   */
  submittedByUserId?: string | null;
  submittedByEmail?: string | null;
  validatedEva?: boolean | null;
  stockValidationPending?: boolean | null;
  exportedToErpAt?: string | null;
  evaRejectionReason?: string | null;
  skaiExternalId?: string | null;
  deliveryMethod?: ('home' | 'alternate_address' | 'pickup_alfaro' | 'pickup_rincon') | null;
  shippingCost?: number | null;
  pickupStoreLabel?: string | null;
  shippingAddressSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  billingAddressSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  couponCode?: string | null;
  couponUsageRecorded?: boolean | null;
  customerNotes?: string | null;
  guestEmail?: string | null;
  paymentMethodCode?: string | null;
  paymentMethodLabel?: string | null;
  paymentStatus?: ('pending' | 'authorized' | 'failed' | 'cancelled') | null;
  gateway?: ('redsys' | 'paypal' | 'transfer' | 'erp') | null;
  gatewayTransactionId?: string | null;
  gatewayAuthCode?: string | null;
  paidAmount?: number | null;
  paidAt?: string | null;
  paymentFailureReason?: string | null;
  /**
   * SKU, cantidades y precios al confirmar desde storefront
   */
  orderLineSnapshots?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  accessToken?: string | null;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Imagen de catálogo (listados y ficha): URL externa del proveedor. La imagen propia tiene prioridad en el storefront. No se usa para Open Graph.
   */
  providerImageUrl?: string | null;
  /**
   * Imagen de catálogo (listados y galería PDP). Prioridad sobre URL de proveedor. Para redes sociales use meta.image en la pestaña SEO Preview.
   */
  ownImage?: (number | null) | Media;
  /**
   * Fotos extra visibles solo en la ficha de producto. La imagen principal sigue siendo «Imagen propia» (o URL de proveedor si no hay propia).
   */
  additionalImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Valor mostrado en filtros del listado de productos (RF-010).
   */
  facetColor?: string | null;
  /**
   * Tipo de material para filtros del listado (RF-010).
   */
  facetMaterial?: string | null;
  /**
   * Producto con etiqueta ecológica en PLP.
   */
  ecoLabel?: boolean | null;
  /**
   * Manuales y fichas técnicas visibles en la ficha de producto (RF-012).
   */
  attachments?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  skuErp?: string | null;
  mainWholesaleRef?: string | null;
  oemRef?: string | null;
  ean?: string | null;
  shortDescription?: string | null;
  p1Price?: number | null;
  p2Price?: number | null;
  vatRate?: number | null;
  packUnit?: number | null;
  isWildcard?: boolean | null;
  allowOrderWithoutStock?: boolean | null;
  /**
   * Unidades disponibles para venta (gestión manual en modo web-native).
   */
  erpStock?: number | null;
  /**
   * Calculado automáticamente al guardar según stock disponible y umbral configurado.
   */
  stockIndicator?: ('available' | 'low' | 'limited') | null;
  /**
   * Solo actualizado por sync ERP cuando el modo web-native está desactivado.
   */
  syncErpAt?: string | null;
  /**
   * Se muestran en la ficha del producto en la tienda (máximo 8). La relación es bidireccional: si A relaciona B, B también quedará relacionado con A al guardar. Debes publicar para que la tienda lea los cambios.
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * Título, descripción e imagen para Open Graph, Twitter y datos estructurados. Si no hay meta.image, el storefront usa la imagen de catálogo (propia o proveedor).
   */
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  supplier?: (number | null) | Supplier;
  categories?: (number | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  erpCode?: string | null;
  type?: ('wholesaler' | 'manufacturer' | 'distributor' | 'other') | null;
  /**
   * Prefijo URL para imágenes del proveedor
   */
  baseImageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  parent?: (number | null) | Category;
  sortOrder?: number | null;
  imageUrl?: string | null;
  /**
   * Icono en la rejilla de categorías destacadas de la tienda.
   */
  homeGlyph?:
    | (
        | 'pen'
        | 'notebook'
        | 'paper'
        | 'toner'
        | 'ink'
        | 'folder'
        | 'binder'
        | 'stapler'
        | 'calc'
        | 'scissors'
        | 'marker'
        | 'tape'
        | 'recycle'
        | 'bin'
        | 'battery'
        | 'printer'
        | 'box'
      )
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'products';
            value: number | Product;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'products';
            value: number | Product;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bandeja operativa: /admin/quotes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  quoteNumber?: string | null;
  status?: ('requested' | 'in_review' | 'sent' | 'accepted' | 'ordered' | 'cancelled') | null;
  segment?: ('b2c' | 'b2b') | null;
  customerRef?: string | null;
  guestEmail?: string | null;
  amount?: number | null;
  subtotal?: number | null;
  shippingCost?: number | null;
  deliveryMethod?: ('home' | 'alternate_address' | 'pickup_alfaro' | 'pickup_rincon') | null;
  pickupStoreLabel?: string | null;
  shippingAddressSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  billingAddressSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  customerNotes?: string | null;
  lineSnapshots?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  validUntil?: string | null;
  emailSentAt?: string | null;
  convertedOrderRef?: (number | null) | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bandeja operativa: /admin/rma
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rma-incidents".
 */
export interface RmaIncident {
  id: number;
  rmaNumber?: string | null;
  status?: ('requested' | 'in_review' | 'authorized' | 'rejected') | null;
  customerRef: string;
  articleSku: string;
  deliveryNoteNumber: string;
  reason: 'wrong_item' | 'defective' | 'wrong_qty' | 'other';
  observations?: string | null;
  emailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Se guarda en mayúsculas (ej. BLOG5)
   */
  code: string;
  discountType: 'percent' | 'fixed';
  /**
   * Porcentaje 1–100 o importe fijo en € (neto)
   */
  discountValue: number;
  minimumOrderAmount?: number | null;
  validFrom: string;
  validUntil: string;
  /**
   * Vacío = ilimitado
   */
  maxUses?: number | null;
  usesCount?: number | null;
  active?: boolean | null;
  source?: ('manual' | 'recovery') | null;
  recoveryCartId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catálogos PDF y revistas de ofertas visibles en /intranet/descargas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "b2b-catalog-downloads".
 */
export interface B2BCatalogDownload {
  id: number;
  title: string;
  description?: string | null;
  documentType: 'catalog' | 'offer_magazine' | 'other';
  /**
   * Solo PDF, máximo 25 MB.
   */
  file: number | Media;
  coverImage?: (number | null) | Media;
  validFrom: string;
  validUntil: string;
  /**
   * Vacío = visible para todos los grupos B2B (2, 3 y 4).
   */
  customerGroups?: ('2' | '3' | '4')[] | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Facturas, albaranes y documentos financieros B2B subidos por administración.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-documents".
 */
export interface CustomerDocument {
  id: number;
  customerId: string;
  documentType: 'invoice' | 'delivery_note' | 'due_payment' | 'form_347' | 'erp_quote';
  documentNumber: string;
  issuedAt: string;
  netAmount?: number | null;
  grossAmount?: number | null;
  dueDate?: string | null;
  outstandingAmount?: number | null;
  status?: string | null;
  pdfFile: number | Media;
  storagePath?: string | null;
  fiscalYear?: number | null;
  validUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-prices".
 */
export interface SpecialPrice {
  id: number;
  customerId: string;
  productSku: string;
  netPrice: number;
  discount1Pct?: number | null;
  discount2Pct?: number | null;
  minQty?: number | null;
  validFrom: string;
  validTo?: string | null;
  supabaseId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-offers".
 */
export interface GroupOffer {
  id: number;
  productSku: string;
  offerNetPrice: number;
  customerGroup?: ('' | '1' | '2' | '3' | '4') | null;
  validFrom: string;
  validTo?: string | null;
  active?: boolean | null;
  supabaseId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'rma-incidents';
        value: number | RmaIncident;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'b2b-catalog-downloads';
        value: number | B2BCatalogDownload;
      } | null)
    | ({
        relationTo: 'customer-documents';
        value: number | CustomerDocument;
      } | null)
    | ({
        relationTo: 'special-prices';
        value: number | SpecialPrice;
      } | null)
    | ({
        relationTo: 'group-offers';
        value: number | GroupOffer;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  staffRoles?: T;
  twoFactorEnabled?: T;
  totpSecret?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  sortOrder?: T;
  imageUrl?: T;
  homeGlyph?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  erpCode?: T;
  type?: T;
  baseImageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  status?: T;
  segment?: T;
  customerRef?: T;
  guestEmail?: T;
  amount?: T;
  subtotal?: T;
  shippingCost?: T;
  deliveryMethod?: T;
  pickupStoreLabel?: T;
  shippingAddressSnapshot?: T;
  billingAddressSnapshot?: T;
  customerNotes?: T;
  lineSnapshots?: T;
  validUntil?: T;
  emailSentAt?: T;
  convertedOrderRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rma-incidents_select".
 */
export interface RmaIncidentsSelect<T extends boolean = true> {
  rmaNumber?: T;
  status?: T;
  customerRef?: T;
  articleSku?: T;
  deliveryNoteNumber?: T;
  reason?: T;
  observations?: T;
  emailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  discountValue?: T;
  minimumOrderAmount?: T;
  validFrom?: T;
  validUntil?: T;
  maxUses?: T;
  usesCount?: T;
  active?: T;
  source?: T;
  recoveryCartId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "b2b-catalog-downloads_select".
 */
export interface B2BCatalogDownloadsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  documentType?: T;
  file?: T;
  coverImage?: T;
  validFrom?: T;
  validUntil?: T;
  customerGroups?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-documents_select".
 */
export interface CustomerDocumentsSelect<T extends boolean = true> {
  customerId?: T;
  documentType?: T;
  documentNumber?: T;
  issuedAt?: T;
  netAmount?: T;
  grossAmount?: T;
  dueDate?: T;
  outstandingAmount?: T;
  status?: T;
  pdfFile?: T;
  storagePath?: T;
  fiscalYear?: T;
  validUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-prices_select".
 */
export interface SpecialPricesSelect<T extends boolean = true> {
  customerId?: T;
  productSku?: T;
  netPrice?: T;
  discount1Pct?: T;
  discount2Pct?: T;
  minQty?: T;
  validFrom?: T;
  validTo?: T;
  supabaseId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-offers_select".
 */
export interface GroupOffersSelect<T extends boolean = true> {
  productSku?: T;
  offerNetPrice?: T;
  customerGroup?: T;
  validFrom?: T;
  validTo?: T;
  active?: T;
  supabaseId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  longDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  providerImageUrl?: T;
  ownImage?: T;
  additionalImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  facetColor?: T;
  facetMaterial?: T;
  ecoLabel?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  skuErp?: T;
  mainWholesaleRef?: T;
  oemRef?: T;
  ean?: T;
  shortDescription?: T;
  p1Price?: T;
  p2Price?: T;
  vatRate?: T;
  packUnit?: T;
  isWildcard?: T;
  allowOrderWithoutStock?: T;
  erpStock?: T;
  stockIndicator?: T;
  syncErpAt?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  supplier?: T;
  categories?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  origin?: T;
  jeyjoStatus?: T;
  customerRef?: T;
  submittedByUserId?: T;
  submittedByEmail?: T;
  validatedEva?: T;
  stockValidationPending?: T;
  exportedToErpAt?: T;
  evaRejectionReason?: T;
  skaiExternalId?: T;
  deliveryMethod?: T;
  shippingCost?: T;
  pickupStoreLabel?: T;
  shippingAddressSnapshot?: T;
  billingAddressSnapshot?: T;
  couponCode?: T;
  couponUsageRecorded?: T;
  customerNotes?: T;
  guestEmail?: T;
  paymentMethodCode?: T;
  paymentMethodLabel?: T;
  paymentStatus?: T;
  gateway?: T;
  gatewayTransactionId?: T;
  gatewayAuthCode?: T;
  paidAmount?: T;
  paidAt?: T;
  paymentFailureReason?: T;
  orderLineSnapshots?: T;
  accessToken?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  promoBanners?:
    | {
        image: number | Media;
        href: string;
        alt?: string | null;
        segment: 'b2c' | 'b2b' | 'both';
        startAt: string;
        endAt: string;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  featuredCategories?: (number | Category)[] | null;
  topSalesB2c?: (number | Product)[] | null;
  topSalesB2b?: (number | Product)[] | null;
  ecoHighlight?: (number | Product)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Parámetros operativos de portes, stock, alertas y contacto. Los cambios se propagan en ~1 minuto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "systemSettings".
 */
export interface SystemSetting {
  id: number;
  shippingB2cThreshold?: number | null;
  shippingB2cCost?: number | null;
  shippingB2bThreshold?: number | null;
  shippingB2bCost?: number | null;
  /**
   * Unidades por debajo de las cuales el indicador es "Últimas unidades".
   */
  stockLowThreshold?: number | null;
  topSalesWindowDays?: number | null;
  dashboardLowStockThreshold?: number | null;
  /**
   * Cuando está activo, catálogo, stock, documentos y tarifas se gestionan solo desde el CMS. Sync ERP y export Avansuite quedan deshabilitados.
   */
  webNativeMode?: boolean | null;
  /**
   * Tras este tiempo sin sync exitoso, los datos se consideran obsoletos.
   */
  catalogStalenessHours?: number | null;
  predictiveSearchEnabled?: boolean | null;
  suggestLimit?: number | null;
  minQueryLength?: number | null;
  supportPhone?: string | null;
  supportEmail?: string | null;
  whatsapp?: string | null;
  storeAlfaroName?: string | null;
  storeAlfaroAddress?: string | null;
  storeRinconName?: string | null;
  storeRinconAddress?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentSettings".
 */
export interface PaymentSetting {
  id: number;
  cardEnabled?: boolean | null;
  bizumEnabled?: boolean | null;
  paypalEnabled?: boolean | null;
  transferEnabled?: boolean | null;
  applePayEnabled?: boolean | null;
  googlePayEnabled?: boolean | null;
  transferInstructions?: {
    iban?: string | null;
    beneficiary?: string | null;
    /**
     * Use {orderNumber} como marcador de referencia
     */
    conceptTemplate?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketingSettings".
 */
export interface MarketingSetting {
  id: number;
  abandonedCartEnabled?: boolean | null;
  /**
   * Por defecto 2 horas
   */
  firstEmailDelayMinutes?: number | null;
  /**
   * Por defecto 24 horas
   */
  secondEmailDelayMinutes?: number | null;
  secondEmailDiscountPercent?: number | null;
  /**
   * Si está vacío, se genera un cupón RECOVER- único de un solo uso
   */
  secondEmailUseFixedCoupon?: (number | null) | Coupon;
  b2bRecoveryEnabled?: boolean | null;
  b2bRecoveryCustomerGroups?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterSettings".
 */
export interface NewsletterSetting {
  id: number;
  enabled?: boolean | null;
  headline?: string | null;
  description?: string | null;
  privacyPolicyUrl?: string | null;
  /**
   * Sustituye BREVO_NEWSLETTER_LIST_ID del entorno si se indica
   */
  brevoListId?: number | null;
  confirmationEmailEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skaiSettings".
 */
export interface SkaiSetting {
  id: number;
  enabled?: boolean | null;
  businessHours?: string | null;
  outOfHoursMessage?: string | null;
  fallbackPhone?: string | null;
  fallbackEmail?: string | null;
  fallbackWhatsapp?: string | null;
  knowledgeDocuments?:
    | {
        filename: string;
        uploadedAt?: string | null;
        storagePath?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsSettings".
 */
export interface AnalyticsSetting {
  id: number;
  /**
   * Documentación operativa. En runtime la tienda usa NEXT_PUBLIC_GA4_MEASUREMENT_ID y NEXT_PUBLIC_GA4_ENABLED (ver apps/storefront/.env.example).
   */
  ga4MeasurementId?: string | null;
  /**
   * Kill switch además de MERCHANT_FEED_ENABLED en Vercel. URL pública: /api/feeds/merchant-center.xml
   */
  merchantFeedEnabled?: boolean | null;
  lastFeedGeneratedAt?: string | null;
  feedOmittedCounts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consecutiveFeedFailures?: number | null;
  lastFeedErrorAt?: string | null;
  lastFeedErrorMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  promoBanners?:
    | T
    | {
        image?: T;
        href?: T;
        alt?: T;
        segment?: T;
        startAt?: T;
        endAt?: T;
        sortOrder?: T;
        id?: T;
      };
  featuredCategories?: T;
  topSalesB2c?: T;
  topSalesB2b?: T;
  ecoHighlight?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "systemSettings_select".
 */
export interface SystemSettingsSelect<T extends boolean = true> {
  shippingB2cThreshold?: T;
  shippingB2cCost?: T;
  shippingB2bThreshold?: T;
  shippingB2bCost?: T;
  stockLowThreshold?: T;
  topSalesWindowDays?: T;
  dashboardLowStockThreshold?: T;
  webNativeMode?: T;
  catalogStalenessHours?: T;
  predictiveSearchEnabled?: T;
  suggestLimit?: T;
  minQueryLength?: T;
  supportPhone?: T;
  supportEmail?: T;
  whatsapp?: T;
  storeAlfaroName?: T;
  storeAlfaroAddress?: T;
  storeRinconName?: T;
  storeRinconAddress?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentSettings_select".
 */
export interface PaymentSettingsSelect<T extends boolean = true> {
  cardEnabled?: T;
  bizumEnabled?: T;
  paypalEnabled?: T;
  transferEnabled?: T;
  applePayEnabled?: T;
  googlePayEnabled?: T;
  transferInstructions?:
    | T
    | {
        iban?: T;
        beneficiary?: T;
        conceptTemplate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketingSettings_select".
 */
export interface MarketingSettingsSelect<T extends boolean = true> {
  abandonedCartEnabled?: T;
  firstEmailDelayMinutes?: T;
  secondEmailDelayMinutes?: T;
  secondEmailDiscountPercent?: T;
  secondEmailUseFixedCoupon?: T;
  b2bRecoveryEnabled?: T;
  b2bRecoveryCustomerGroups?:
    | T
    | {
        code?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterSettings_select".
 */
export interface NewsletterSettingsSelect<T extends boolean = true> {
  enabled?: T;
  headline?: T;
  description?: T;
  privacyPolicyUrl?: T;
  brevoListId?: T;
  confirmationEmailEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skaiSettings_select".
 */
export interface SkaiSettingsSelect<T extends boolean = true> {
  enabled?: T;
  businessHours?: T;
  outOfHoursMessage?: T;
  fallbackPhone?: T;
  fallbackEmail?: T;
  fallbackWhatsapp?: T;
  knowledgeDocuments?:
    | T
    | {
        filename?: T;
        uploadedAt?: T;
        storagePath?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsSettings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  ga4MeasurementId?: T;
  merchantFeedEnabled?: T;
  lastFeedGeneratedAt?: T;
  feedOmittedCounts?: T;
  consecutiveFeedFailures?: T;
  lastFeedErrorAt?: T;
  lastFeedErrorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}